//! GENERATED oracle test — do not hand-edit the cases.
//!
//! PROVENANCE: one case per signature in zephem's map that carries inline `///` prose (the
//! entire population for the pinned zig, not a sample). The expected arity of each was derived
//! from the compiler's OWN SOURCE: the declaration at the map's file:line, `///` lines dropped,
//! parameters counted independently of the implementation under test. This test was run against
//! the pre-fix arityOf and failed, proving it bites.
//!
//! When zephem's map is regenerated for a new Zig, regenerate this file the same way —
//! a test fitted to a stale population silently stops covering the real one.
const std = @import("std");
const zephem = @import("zcanon").zephem;
test "oracle: arity of all 68 prose-bearing sigs" {
    const gpa = std.testing.allocator;
    try std.testing.expectEqual(@as(?usize, 2), zephem.arityOf(gpa, "fn updateTimeReportCompile(ws: *WebServer, opts: struct { compile: *Build.Step.Compile, use_llvm: bool, stats: abi.time_report.CompileResult.Stats, ns_total: u64, llvm_pass_timings_len: u32, files_len: u32, decls_len: u32, /// The trailing data of `abi.time_report.CompileResult`, except the step name. trailing: []const u8, }) void")); // std.Build.WebServer.updateTimeReportCompile
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn addUserInputOptionFromArg( arena: Allocator, map: *UserInputOptionsMap, field: std.builtin.Type.StructField, comptime T: type, /// If null, the value won't be added, but `T` will still be type-checked. maybe_value: ?T, ) void")); // std.Build.addUserInputOptionFromArg
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn lazyImport( b: *Build, /// The build.zig struct of the package importing the dependency. /// When calling this function from the `build` function of a build.zig file's, you normally /// pass `@This()`. comptime asking_build_zig: type, comptime dep_name: []const u8, ) ?type")); // std.Build.lazyImport
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn dependencyFromBuildZig( b: *Build, /// The build.zig struct of the dependency, normally obtained by `@import` of the dependency. /// If called from the build.zig file itself, use `@This` to obtain a reference to the struct. comptime build_zig: type, args: anytype, ) *Dependency")); // std.Build.dependencyFromBuildZig
    try std.testing.expectEqual(@as(?usize, 2), zephem.arityOf(gpa, "fn init( /// Must be threadsafe. Only used for the following functions: /// * `Io.VTable.async` /// * `Io.VTable.concurrent` /// * `Io.VTable.groupAsync` /// * `Io.VTable.groupConcurrent` /// If these functions are avoided, then `Allocator.failing` may be passed /// here. gpa: Allocator, options: InitOptions, ) Threaded")); // std.Io.Threaded.init
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn argvToScriptCommandLineWindows( allocator: Allocator, /// Path to the `.bat`/`.cmd` script. If this path is relative, it is assumed to be relative to the CWD. /// The script must have been verified to exist at this path before calling this function. script_path: []const u16, /// Arguments, not including the script name itself. Expected to be encoded as WTF-8. script_args: []const []const u8, ) ArgvToScriptCommandLineError![:0]u16")); // std.Io.Threaded.argvToScriptCommandLineWindows
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn park( timeout: Io.Timeout, /// This value has no semantic effect, but may allow the OS to optimize the operation. addr_hint: ?*const anyopaque, unpark_flag: if (need_unpark_flag) *UnparkFlag else void, ) error{Timeout}!void")); // std.Io.Threaded.park
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn receiveManyTimeout( s: *const Socket, io: Io, /// Function assumes each element has initialized `control` field. /// Initializing with `IncomingMessage.init` may be helpful. message_buffer: []IncomingMessage, data_buffer: []u8, flags: ReceiveFlags, timeout: Io.Timeout, ) struct { ?ReceiveTimeoutError, usize }")); // std.Io.net.Socket.receiveManyTimeout
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn updateFile( source_dir: Dir, io: Io, source_path: []const u8, dest_dir: Dir, /// If directories in this path do not exist, they are created. dest_path: []const u8, options: CopyFileOptions, ) !PrevStatus")); // std.Io.Dir.updateFile
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn readFileAlloc( dir: Dir, io: Io, /// On Windows, should be encoded as [WTF-8](https://wtf-8.codeberg.page/). /// On WASI, should be encoded as valid UTF-8. /// On other platforms, an opaque sequence of bytes with no particular encoding. sub_path: []const u8, /// Used to allocate the result. gpa: Allocator, /// If reached or exceeded, `error.StreamTooLong` is returned instead. limit: Io.Limit, ) ReadFileAllocError![]u8")); // std.Io.Dir.readFileAlloc
    try std.testing.expectEqual(@as(?usize, 7), zephem.arityOf(gpa, "fn readFileAllocOptions( dir: Dir, io: Io, /// On Windows, should be encoded as [WTF-8](https://wtf-8.codeberg.page/). /// On WASI, should be encoded as valid UTF-8. /// On other platforms, an opaque sequence of bytes with no particular encoding. sub_path: []const u8, /// Used to allocate the result. gpa: Allocator, /// If reached or exceeded, `error.StreamTooLong` is returned instead. limit: Io.Limit, comptime alignment: std.mem.Alignment, comptime sentinel: ?u8, ) ReadFileAllocError!(if (sentinel) |s| [:s]align(alignment.toByteUnits()) u8 else []align(alignment.toByteUnits()) u8)")); // std.Io.Dir.readFileAllocOptions
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn Custom( comptime K: type, comptime V: type, /// A namespace that provides these two functions: /// * `pub fn hash(self, K) u32` /// * `pub fn eql(self, K, K, usize) bool` /// /// The final `usize` in the `eql` function represents the index of the key /// that's already inside the map. comptime Context: type, /// When `false`, this data structure is biased towards cheap `eql` /// functions and avoids storing each key's hash in the table. Setting /// `store_hash` to `true` incurs more memory cost but limits `eql` to /// being called only once per insertion/deletion (provided there are no /// hash collisions). comptime store_hash: bool, ) type")); // std.array_hash_map.Custom
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn getaddrinfo( noalias node: ?[*:0]const u8, noalias service: ?[*:0]const u8, noalias hints: ?*const addrinfo, /// On Linux, `res` will not be modified on error and `freeaddrinfo` will /// potentially crash if you pass it an undefined pointer noalias res: *?*addrinfo, ) EAI")); // std.c.getaddrinfo
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn process( self: *Decode, reader: *Reader, allocating: *Writer.Allocating, /// `CircularBuffer` or `std.compress.lzma2.AccumBuffer`. buffer: anytype, decoder: *RangeDecoder, n_read: *u64, ) !ProcessingStatus")); // std.compress.lzma.Decode.process
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn decodeLiteral( self: *Decode, reader: *Reader, /// `CircularBuffer` or `std.compress.lzma2.AccumBuffer`. buffer: anytype, decoder: *RangeDecoder, n_read: *u64, ) !u8")); // std.compress.lzma.Decode.decodeLiteral
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn init( input: *Reader, gpa: Allocator, /// Decompress takes ownership of this buffer and resizes it with `gpa`. buffer: []u8, ) !Decompress")); // std.compress.xz.Decompress.init
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn signerWithBaseNonce( key_pair: KeyPair, base_nonce: [32]u8, /// If set, should be something unique for each message, such as a counter. noise: ?[noise_length]u8, ) (IdentityElementError || KeyMismatchError || NonCanonicalError || WeakPublicKeyError)!Signer")); // std.crypto.sign.Ed25519.KeyPair.signerWithBaseNonce
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn signer( key_pair: KeyPair, /// If set, should be something unique for each message, such as a /// random nonce, or a counter. noise: ?[noise_length]u8, io: std.Io, ) (IdentityElementError || KeyMismatchError || NonCanonicalError || WeakPublicKeyError)!Signer")); // std.crypto.sign.Ed25519.KeyPair.signer
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn parse( /// The virtual address of the FDE we're parsing, *excluding* its entry header (i.e. the /// address is after the header). If `fde_bytes` is backed by the memory of a loaded /// module's `.eh_frame` section, this will equal `fde_bytes.ptr`. fde_vaddr: u64, fde_bytes: []const u8, cie: *const CommonInformationEntry, endian: Endian, ) !FrameDescriptionEntry")); // std.debug.Dwarf.Unwind.FrameDescriptionEntry.parse
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn prepare( unwind: *Unwind, gpa: Allocator, addr_size_bytes: u8, endian: Endian, need_lookup: bool, /// The `__eh_frame` section in Mach-O binaries deviates from the standard `.eh_frame` section /// in one way which this function needs to be aware of. is_macho: bool, ) !void")); // std.debug.Dwarf.Unwind.prepare
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn resolveAddresses( info: *Info, gpa: Allocator, io: Io, /// Asserts the addresses are in ascending order. sorted_pc_addrs: []const u64, /// Asserts its length equals length of `sorted_pc_addrs`. output: []SourceLocation, ) ResolveAddressesError!void")); // std.debug.Info.resolveAddresses
    try std.testing.expectEqual(@as(?usize, 7), zephem.arityOf(gpa, "fn resolveAddressesDwarf( cov: *Coverage, gpa: Allocator, io: Io, endian: std.builtin.Endian, /// Asserts the addresses are in ascending order. sorted_pc_addrs: []const u64, /// Asserts its length equals length of `sorted_pc_addrs`. output: []SourceLocation, d: *Dwarf, ) ResolveAddressesDwarfError!void")); // std.debug.Coverage.resolveAddressesDwarf
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn allocWithOptions( self: Allocator, comptime Elem: type, n: usize, /// null means naturally aligned comptime optional_alignment: ?Alignment, comptime optional_sentinel: ?Elem, ) Error!AllocWithOptionsPayload(Elem, optional_alignment, optional_sentinel)")); // std.mem.Allocator.allocWithOptions
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn allocWithOptionsRetAddr( self: Allocator, comptime Elem: type, n: usize, /// null means naturally aligned comptime optional_alignment: ?Alignment, comptime optional_sentinel: ?Elem, return_address: usize, ) Error!AllocWithOptionsPayload(Elem, optional_alignment, optional_sentinel)")); // std.mem.Allocator.allocWithOptionsRetAddr
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn alignedAlloc( self: Allocator, comptime T: type, /// null means naturally aligned comptime alignment: ?Alignment, n: usize, ) Error![]align(if (alignment) |a| a.toByteUnits() else @alignOf(T)) T")); // std.mem.Allocator.alignedAlloc
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn allocAdvancedWithRetAddr( self: Allocator, comptime T: type, /// null means naturally aligned comptime alignment: ?Alignment, n: usize, return_address: usize, ) Error![]align(if (alignment) |a| a.toByteUnits() else @alignOf(T)) T")); // std.mem.Allocator.allocAdvancedWithRetAddr
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn futex2_waitv( futexes: [*]const futex2_waitone, /// Length of `futexes`. Max of FUTEX2_WAITONE_MAX. nr_futexes: u32, flags: FUTEX2_FLAGS_WAITV, /// Optional absolute timeout. Always 64-bit, even on 32-bit platforms. timeout: ?*const kernel_timespec, /// Clock to be used for the timeout, realtime or monotonic. clockid: clockid_t, ) usize")); // std.os.linux.futex2_waitv
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn futex2_wait( /// Address of the futex to wait on. uaddr: *const anyopaque, /// Value of `uaddr`. val: usize, /// Bitmask to match against incoming wakeup masks. Must not be zero. mask: usize, flags: FUTEX2_FLAGS, /// Optional absolute timeout. Always 64-bit, even on 32-bit platforms. timeout: ?*const kernel_timespec, /// Clock to be used for the timeout, realtime or monotonic. clockid: clockid_t, ) usize")); // std.os.linux.futex2_wait
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn futex2_wake( /// Futex to wake uaddr: *const anyopaque, /// Bitmask to match against waiters. mask: usize, /// Maximum number of waiters on the futex to wake. nr_wake: i32, flags: FUTEX2_FLAGS, ) usize")); // std.os.linux.futex2_wake
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn futex2_requeue( /// The source and destination futexes. Must be a 2-element array. waiters: [*]const futex2_waitone, /// Currently unused. flags: FUTEX2_FLAGS_REQUEUE, /// Maximum number of waiters to wake on the source futex. nr_wake: i32, /// Maximum number of waiters to transfer to the destination futex. nr_requeue: i32, ) usize")); // std.os.linux.futex2_requeue
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn cachestat( /// The open file descriptor to retrieve statistics from. fd: fd_t, /// The byte range in `fd` to query. /// When `len > 0`, the range is `[off..off + len]`. /// When `len` == 0, the range is from `off` to the end of `fd`. cstat_range: *const cache_stat_range, /// The structure where page cache statistics are stored. cstat: *cache_stat, /// Currently unused, and must be set to `0`. flags: u32, ) usize")); // std.os.linux.cachestat
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn NtSetInformationFile( FileHandle: HANDLE, IoStatusBlock: *IO_STATUS_BLOCK, /// This can't be const as providing read-only memory could result in ACCESS_VIOLATION /// in certain scenarios. This has been seen when using FILE_DISPOSITION_INFORMATION_EX /// and targeting x86-windows. FileInformation: *anyopaque, Length: ULONG, FileInformationClass: FILE.INFORMATION_CLASS, ) callconv(.winapi) NTSTATUS")); // std.os.windows.ntdll.NtSetInformationFile
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn NtQueryValueKey( KeyHandle: HANDLE, ValueName: *const UNICODE_STRING, KeyValueInformationClass: KEY.VALUE.INFORMATION_CLASS, KeyValueInformation: *anyopaque, /// Length of KeyValueInformation buffer in bytes Length: ULONG, /// On STATUS_SUCCESS, contains the length of the populated portion of the /// provided buffer. On STATUS_BUFFER_OVERFLOW or STATUS_BUFFER_TOO_SMALL, /// contains the minimum `Length` value that would be required to hold the information. ResultLength: *ULONG, ) callconv(.winapi) NTSTATUS")); // std.os.windows.ntdll.NtQueryValueKey
    try std.testing.expectEqual(@as(?usize, 11), zephem.arityOf(gpa, "fn NtCreateThreadEx( ThreadHandle: *HANDLE, DesiredAccess: ACCESS_MASK, ObjectAttributes: *const OBJECT.ATTRIBUTES, ProcessHandle: HANDLE, StartRoutine: *const USER_THREAD_START_ROUTINE, Argument: ?PVOID, CreateFlags: THREAD.CREATE_FLAGS, ZeroBits: SIZE_T, /// This value is rounded up to the nearest page. /// If this value is larger than `StackReserve`, the reserved stack /// size will be the rounded value of this parameter. /// https://learn.microsoft.com/en-us/windows/win32/procthread/thread-stack-size StackCommit: THREAD.StackSize, StackReserve: THREAD.StackSize, AttributeList: ?*PS.ATTRIBUTE.LIST, ) callconv(.winapi) NTSTATUS")); // std.os.windows.ntdll.NtCreateThreadEx
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn prefixScanWithFunc( comptime hop: isize, vec: anytype, /// The error type that `func` might return. Set this to `void` if `func` doesn't return an error union. comptime ErrorType: type, comptime func: fn (@TypeOf(vec), @TypeOf(vec)) if (ErrorType == void) @TypeOf(vec) else ErrorType!@TypeOf(vec), /// When one operand of the operation performed by `func` is this value, the result must equal the other operand. /// For example, this should be 0 for addition or 1 for multiplication. comptime identity: std.meta.Child(@TypeOf(vec)), ) if (ErrorType == void) @TypeOf(vec) else ErrorType!@TypeOf(vec)")); // std.simd.prefixScanWithFunc
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn writeFileTimestamp( w: *Writer, /// Assumed to use `/` for any path separators. sub_path: []const u8, file_reader: *Io.File.Reader, mtime: Io.Timestamp, ) WriteFileError!void")); // std.tar.Writer.writeFileTimestamp
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn writeFile( w: *Writer, /// Assumed to use `/` for any path separators. sub_path: []const u8, file_reader: *Io.File.Reader, /// If you want to match the file format's expectations, it wants number of /// seconds since POSIX epoch. Zero is also a great option here to make /// generated tarballs more reproducible. mtime: u64, ) WriteFileError!void")); // std.tar.Writer.writeFile
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn writeFileStream( w: *Writer, /// Assumed to use `/` for any path separators. sub_path: []const u8, size: u64, reader: *Io.Reader, options: Options, ) WriteFileStreamError!void")); // std.tar.Writer.writeFileStream
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn writeFileBytes( w: *Writer, /// Assumed to use `/` for all path separators. sub_path: []const u8, content: []const u8, options: Options, ) Error!void")); // std.tar.Writer.writeFileBytes
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn testEpoch(secs: u64, expected_year_day: YearAndDay, expected_month_day: MonthAndDay, expected_day_seconds: struct { /// 0 to 23 hours_into_day: u5, /// 0 to 59 minutes_into_hour: u6, /// 0 to 59 seconds_into_minute: u6, }) !void")); // std.time.epoch.testEpoch
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn renderVarDecl( r: *Render, var_decl: Ast.full.VarDecl, /// Destructures intentionally ignore leading `comptime` tokens. ignore_comptime_token: bool, /// `comma_space` and `space` are used for destructure LHS decls. space: Space, ) Error!void")); // std.zig.Ast.Render.renderVarDecl
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn renderVarDeclWithoutFixups( r: *Render, var_decl: Ast.full.VarDecl, /// Destructures intentionally ignore leading `comptime` tokens. ignore_comptime_token: bool, /// `comma_space` and `space` are used for destructure LHS decls. space: Space, ) Error!void")); // std.zig.Ast.Render.renderVarDeclWithoutFixups
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn reachableExprComptime( gz: *GenZir, scope: *Scope, ri: ResultInfo, node: Ast.Node.Index, reachable_node: Ast.Node.Index, /// If `null`, the expression is not evaluated in a comptime context. comptime_reason: ?std.zig.SimpleComptimeReason, ) InnerError!Zir.Inst.Ref")); // std.zig.AstGen.reachableExprComptime
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn tunnelThroughClosure( gz: *GenZir, /// The node which references the value to be captured. inner_ref_node: Ast.Node.Index, /// The number of namespaces being tunnelled through. At least 1. num_tunnels: u32, /// The value being captured. value: union(enum) { ref: Zir.Inst.Ref, ref_load: Zir.Inst.Ref, decl_val: Zir.NullTerminatedString, decl_ref: Zir.NullTerminatedString, }, /// The location of the value's declaration. decl_src: union(enum) { token: Ast.TokenIndex, node: Ast.Node.Index, }, name_str_index: Zir.NullTerminatedString, ) !Zir.Inst.Ref")); // std.zig.AstGen.tunnelThroughClosure
    try std.testing.expectEqual(@as(?usize, 6), zephem.arityOf(gpa, "fn callExpr( gz: *GenZir, scope: *Scope, ri: ResultInfo, /// If this is not `.none` and this call is a decl literal form (`.foo(...)`), then this /// type is used as the decl literal result type instead of the result type from `ri.rl`. override_decl_literal_type: Zir.Inst.Ref, node: Ast.Node.Index, call: Ast.full.Call, ) InnerError!Zir.Inst.Ref")); // std.zig.AstGen.callExpr
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn calleeExpr( gz: *GenZir, scope: *Scope, call_rl: ResultInfo.Loc, /// If this is not `.none` and this call is a decl literal form (`.foo(...)`), then this /// type is used as the decl literal result type instead of the result type from `call_rl`. override_decl_literal_type: Zir.Inst.Ref, node: Ast.Node.Index, ) InnerError!Callee")); // std.zig.AstGen.calleeExpr
    try std.testing.expectEqual(@as(?usize, 2), zephem.arityOf(gpa, "fn addFunc( gz: *GenZir, args: struct { src_node: Ast.Node.Index, lbrace_line: u32 = 0, lbrace_column: u32 = 0, param_block: Zir.Inst.Index, ret_gz: ?*GenZir, body_gz: ?*GenZir, cc_gz: ?*GenZir, ret_param_refs: []Zir.Inst.Index, param_insts: []Zir.Inst.Index, // refs to params in `body_gz` should still be in `astgen.ref_table` ret_ty_is_generic: bool, cc_ref: Zir.Inst.Ref, ret_ref: Zir.Inst.Ref, noalias_bits: u32, is_var_args: bool, is_inferred_error: bool, is_noinline: bool, /// Ignored if `body_gz == null`. proto_hash: std.zig.SrcHash, }, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addFunc
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn addUnNode( gz: *GenZir, tag: Zir.Inst.Tag, operand: Zir.Inst.Ref, /// Absolute node index. This function does the conversion to offset from Decl. src_node: Ast.Node.Index, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addUnNode
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn makeUnNode( gz: *GenZir, tag: Zir.Inst.Tag, operand: Zir.Inst.Ref, /// Absolute node index. This function does the conversion to offset from Decl. src_node: Ast.Node.Index, ) !Zir.Inst.Index")); // std.zig.AstGen.GenZir.makeUnNode
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn addPlNode( gz: *GenZir, tag: Zir.Inst.Tag, /// Absolute node index. This function does the conversion to offset from Decl. src_node: Ast.Node.Index, extra: anytype, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addPlNode
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn addPlNodePayloadIndex( gz: *GenZir, tag: Zir.Inst.Tag, /// Absolute node index. This function does the conversion to offset from Decl. src_node: Ast.Node.Index, payload_index: u32, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addPlNodePayloadIndex
    try std.testing.expectEqual(@as(?usize, 7), zephem.arityOf(gpa, "fn addParam( gz: *GenZir, param_gz: *GenZir, /// Previous parameters, which might be referenced in `param_gz` (the new parameter type). /// `ref`s of these instructions will be put into this param's type body, and removed from `AstGen.ref_table`. prev_param_insts: []const Zir.Inst.Index, ty_is_generic: bool, tag: Zir.Inst.Tag, /// Absolute token index. This function does the conversion to Decl offset. abs_tok_index: Ast.TokenIndex, name: Zir.NullTerminatedString, ) !Zir.Inst.Index")); // std.zig.AstGen.GenZir.addParam
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn addUnTok( gz: *GenZir, tag: Zir.Inst.Tag, operand: Zir.Inst.Ref, /// Absolute token index. This function does the conversion to Decl offset. abs_tok_index: Ast.TokenIndex, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addUnTok
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn makeUnTok( gz: *GenZir, tag: Zir.Inst.Tag, operand: Zir.Inst.Ref, /// Absolute token index. This function does the conversion to Decl offset. abs_tok_index: Ast.TokenIndex, ) !Zir.Inst.Index")); // std.zig.AstGen.GenZir.makeUnTok
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn addStrTok( gz: *GenZir, tag: Zir.Inst.Tag, str_index: Zir.NullTerminatedString, /// Absolute token index. This function does the conversion to Decl offset. abs_tok_index: Ast.TokenIndex, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addStrTok
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn addNode( gz: *GenZir, tag: Zir.Inst.Tag, /// Absolute node index. This function does the conversion to offset from Decl. src_node: Ast.Node.Index, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addNode
    try std.testing.expectEqual(@as(?usize, 4), zephem.arityOf(gpa, "fn addInstNode( gz: *GenZir, tag: Zir.Inst.Tag, inst: Zir.Inst.Index, /// Absolute node index. This function does the conversion to offset from Decl. src_node: Ast.Node.Index, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addInstNode
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn addNodeExtended( gz: *GenZir, opcode: Zir.Inst.Extended, /// Absolute node index. This function does the conversion to offset from Decl. src_node: Ast.Node.Index, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addNodeExtended
    try std.testing.expectEqual(@as(?usize, 2), zephem.arityOf(gpa, "fn addAllocExtended( gz: *GenZir, args: struct { /// Absolute node index. This function does the conversion to offset from Decl. node: Ast.Node.Index, type_inst: Zir.Inst.Ref, align_inst: Zir.Inst.Ref, is_const: bool, is_comptime: bool, }, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addAllocExtended
    try std.testing.expectEqual(@as(?usize, 2), zephem.arityOf(gpa, "fn addAsm( gz: *GenZir, args: struct { tag: Zir.Inst.Extended, /// Absolute node index. This function does the conversion to offset from Decl. node: Ast.Node.Index, asm_source: Zir.NullTerminatedString, output_type_bits: u32, is_volatile: bool, outputs: []const Zir.Inst.Asm.Output, inputs: []const Zir.Inst.Asm.Input, clobbers: Zir.Inst.Ref, }, ) !Zir.Inst.Ref")); // std.zig.AstGen.GenZir.addAsm
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn setStruct(gz: *GenZir, inst: Zir.Inst.Index, args: struct { src_node: Ast.Node.Index, name_strat: Zir.Inst.NameStrategy, layout: std.builtin.Type.ContainerLayout, backing_int_type_body_len: ?u32, decls_len: u32, fields_len: u32, any_field_aligns: bool, any_field_defaults: bool, any_comptime_fields: bool, fields_hash: std.zig.SrcHash, captures: []const Zir.Inst.Capture, capture_names: []const Zir.NullTerminatedString, /// The trailing declaration list, field information, and body instructions. remaining: []const u32, }) !void")); // std.zig.AstGen.GenZir.setStruct
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn setUnion(gz: *GenZir, inst: Zir.Inst.Index, args: struct { src_node: Ast.Node.Index, name_strat: Zir.Inst.NameStrategy, kind: Zir.Inst.UnionDecl.Kind, arg_type_body_len: ?u32, decls_len: u32, fields_len: u32, any_field_aligns: bool, any_field_values: bool, fields_hash: std.zig.SrcHash, captures: []const Zir.Inst.Capture, capture_names: []const Zir.NullTerminatedString, /// The trailing declaration list, field information, and body instructions. remaining: []const u32, }) !void")); // std.zig.AstGen.GenZir.setUnion
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn setEnum(gz: *GenZir, inst: Zir.Inst.Index, args: struct { src_node: Ast.Node.Index, name_strat: Zir.Inst.NameStrategy, tag_type_body_len: ?u32, nonexhaustive: bool, decls_len: u32, fields_len: u32, any_field_values: bool, fields_hash: std.zig.SrcHash, captures: []const Zir.Inst.Capture, capture_names: []const Zir.NullTerminatedString, /// The trailing declaration list, field information, and body instructions. remaining: []const u32, }) !void")); // std.zig.AstGen.GenZir.setEnum
    try std.testing.expectEqual(@as(?usize, 2), zephem.arityOf(gpa, "fn setDeclaration( decl_inst: Zir.Inst.Index, args: struct { src_hash: std.zig.SrcHash, src_line: u32, src_column: u32, kind: Zir.Inst.Declaration.Unwrapped.Kind, name: Zir.NullTerminatedString, is_pub: bool, is_threadlocal: bool, linkage: Zir.Inst.Declaration.Unwrapped.Linkage, lib_name: Zir.NullTerminatedString = .empty, type_gz: *GenZir, /// Must be stacked on `type_gz`. align_gz: *GenZir, /// Must be stacked on `align_gz`. linksection_gz: *GenZir, /// Must be stacked on `linksection_gz`. addrspace_gz: *GenZir, /// Must be stacked on `addrspace_gz` and have nothing stacked on top of it. value_gz: *GenZir, }, ) !void")); // std.zig.AstGen.setDeclaration
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn pegGenericLine( a: *AstSmith, prefix: []const u8, /// Adds constraints to what the line contains prefix_kind: enum { any, line_comment, doc_comment }, ) SourceError!void")); // std.zig.AstSmith.pegGenericLine
    try std.testing.expectEqual(@as(?usize, 5), zephem.arityOf(gpa, "fn fromSliceAlloc( /// The type to deserialize into. May not be or contain any of the following types: /// * Any comptime-only type, except in a comptime field /// * `type` /// * `void`, except as a union payload /// * `noreturn` /// * An error set/error union /// * A many-pointer or C-pointer /// * An opaque type, including `anyopaque` /// * An async frame type, including `anyframe` and `anyframe->T` /// * A function /// /// All other types are valid. Unsupported types will fail at compile time. T: type, gpa: Allocator, source: [:0]const u8, diag: ?*Diagnostics, options: Options, ) error{ OutOfMemory, ParseZon }!T")); // std.zon.parse.fromSliceAlloc
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn canParseTypeInner( T: type, /// Visited structs and unions, to avoid infinite recursion. /// Tracking more types is unnecessary, and a little complex due to optional nesting. visited: []const type, parent_is_optional: bool, ) bool")); // std.zon.parse.canParseTypeInner
    try std.testing.expectEqual(@as(?usize, 3), zephem.arityOf(gpa, "fn canSerializeTypeInner( T: type, /// Visited structs and unions, to avoid infinite recursion. /// Tracking more types is unnecessary, and a little complex due to optional nesting. visited: []const type, parent_is_optional: bool, ) bool")); // std.zon.Serializer.canSerializeTypeInner
}
